---
- name: Load tasks from asdf.yml
  import_tasks: asdf.yml
#- name: Load tasks from mongodb.yml
#  import_tasks: mongodb.yml
#
#- name: Load tasks from shirasagi.yml
#  import_tasks: shirasagi.yml
